# Generated by Django 4.2.7 on 2024-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_number', models.CharField(max_length=8)),
                ('ticket_code', models.CharField(max_length=12)),
                ('number_of_tickets', models.IntegerField(default=1)),
            ],
        ),
    ]
