# Generated by Django 4.2.7 on 2024-05-02 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0005_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 10, 48, 13, 32128)),
        ),
    ]
