# Generated by Django 4.2.7 on 2024-05-05 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0008_ticket_purchase_datetime_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 13, 34, 580685)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_datetime',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 12, 13, 34, 580685)),
        ),
    ]
