# Generated by Django 4.2.7 on 2024-05-13 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventmanagement', '0011_alter_ticket_date_alter_ticket_purchase_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=255)),
                ('timerecord', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
