# Generated by Django 4.2.7 on 2024-05-13 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0012_alter_useractivity_timestamp_userrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='http_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='request_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
