# Generated by Django 4.2.7 on 2024-05-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0013_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_desc', models.CharField(max_length=255)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanagement.ticket')),
            ],
        ),
    ]
