# Generated by Django 4.2.7 on 2024-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0014_eventactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventactivity',
            name='email_record',
            field=models.EmailField(default=True, max_length=50),
        ),
    ]
