# Generated by Django 4.2.7 on 2024-05-14 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0015_eventactivity_email_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCallOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callout_time', models.CharField(default=django.utils.timezone.now)),
            ],
        ),
    ]
