# Generated by Django 4.2.7 on 2024-05-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0017_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventactivity',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCallOut',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventActivity',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
