# Generated by Django 4.2.7 on 2024-05-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0018_remove_eventactivity_ticket_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
